from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import joblib
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse
from pathlib import Path

# ==================================================
# TRUTHLENS AI - ML + VERIFICATION BACKEND
# ==================================================

app = Flask(__name__, static_folder=".", static_url_path="")
CORS(app)

# ==================================================
# FILE PATHS
# ==================================================

BASE_DIR = Path(__file__).resolve().parent

MODEL_PATH = BASE_DIR / "truthlens_model.pkl"
VECTORIZER_PATH = BASE_DIR / "truthlens_vectorizer.pkl"

print("======================================")
print("          TRUTHLENS AI BACKEND")
print("======================================")

print("Loading trained model...")

model = joblib.load(MODEL_PATH)
vectorizer = joblib.load(VECTORIZER_PATH)

print("Model loaded successfully!")
print("Vectorizer loaded successfully!")

# ==================================================
# WEBSITE
# ==================================================

@app.route("/")
def index():
    return send_from_directory(BASE_DIR, "index.html")


# ==================================================
# HEALTH CHECK
# ==================================================

@app.route("/api")
def api_status():
    return jsonify({
        "status": "online",
        "message": "TruthLens AI ML backend is running."
    })


# ==================================================
# PREDICTION FUNCTION
# ==================================================

def run_prediction():

    data = request.get_json(silent=True)

    if not data:
        return jsonify({
            "error": "No data received."
        }), 400

    text = data.get("text", "").strip()
    url = data.get("url", "").strip()

    if not text:
        return jsonify({
            "error": "Please enter a news claim."
        }), 400

    # Convert text into numerical format
    text_vector = vectorizer.transform([text])

    # ML prediction
    prediction = model.predict(text_vector)[0]

    # Prediction probabilities
    probabilities = model.predict_proba(text_vector)[0]

    fake_probability = float(probabilities[0])
    real_probability = float(probabilities[1])

    # ==================================================
    # DETERMINE VERDICT
    # ==================================================

    if prediction == 0:

        confidence = fake_probability

        if confidence >= 0.65:
            result = "FAKE"
        else:
            result = "UNCERTAIN"

    else:

        confidence = real_probability

        if confidence >= 0.65:
            result = "REAL"
        else:
            result = "UNCERTAIN"

    confidence_percentage = round(confidence * 100, 2)

    # ==================================================
    # SEND RESULT
    # ==================================================

    return jsonify({
        "result": result,
        "confidence": confidence_percentage,
        "fake_probability": round(fake_probability * 100, 2),
        "real_probability": round(real_probability * 100, 2),
        "article_url": url,
        "message": "Prediction generated by the TruthLens machine-learning model."
    })


# ==================================================
# PREDICTION API
# ==================================================

@app.route("/predict", methods=["POST"])
def predict():
    return run_prediction()


# This matches the URL used by your deployed detector.html
@app.route("/api/predict", methods=["POST"])
def api_predict():
    return run_prediction()


# ==================================================
# SOURCE VERIFICATION
# ==================================================

def run_verification():

    data = request.get_json(silent=True)

    if not data:
        return jsonify({
            "error": "No verification data received."
        }), 400

    url = data.get("url", "").strip()

    # --------------------------------------------------
    # No URL
    # --------------------------------------------------

    if not url:
        return jsonify({
            "success": False,
            "status": "NO_SOURCE",
            "message": "No article URL was provided.",
            "source_accessible": False,
            "title": "",
            "text_preview": ""
        })

    # --------------------------------------------------
    # Basic URL validation
    # --------------------------------------------------

    parsed = urlparse(url)

    if parsed.scheme not in ["http", "https"]:
        return jsonify({
            "success": False,
            "status": "INVALID_URL",
            "message": "The supplied source URL is not valid.",
            "source_accessible": False,
            "title": "",
            "text_preview": ""
        }), 400

    # --------------------------------------------------
    # Try to access source
    # --------------------------------------------------

    try:

        headers = {
            "User-Agent":
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 "
                "(KHTML, like Gecko) "
                "Chrome/150.0 Safari/537.36"
        }

        response = requests.get(
            url,
            headers=headers,
            timeout=10
        )

        # --------------------------------------------------
        # HTTP error
        # --------------------------------------------------

        if response.status_code >= 400:
            return jsonify({
                "success": False,
                "status": "SOURCE_ERROR",
                "message":
                    "The source returned HTTP status "
                    + str(response.status_code)
                    + ".",
                "source_accessible": False,
                "title": "",
                "text_preview": ""
            })

        # --------------------------------------------------
        # Parse webpage
        # --------------------------------------------------

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # Remove unnecessary elements
        for element in soup(
            ["script", "style", "noscript"]
        ):
            element.decompose()

        # Get page title
        title = ""

        if soup.title:
            title = soup.title.get_text(
                strip=True
            )

        # Get visible text
        page_text = soup.get_text(
            separator=" ",
            strip=True
        )

        # Clean whitespace
        page_text = " ".join(
            page_text.split()
        )

        # Create preview
        text_preview = page_text[:1000]

        # --------------------------------------------------
        # Successful retrieval
        # --------------------------------------------------

        return jsonify({
            "success": True,
            "status": "SOURCE_ACCESSIBLE",
            "message":
                "The article page was successfully accessed.",
            "source_accessible": True,
            "title": title,
            "text_preview": text_preview,
            "source_url": url
        })

    # --------------------------------------------------
    # Connection error
    # --------------------------------------------------

    except requests.exceptions.RequestException as error:

        print("Source request error:", error)

        return jsonify({
            "success": False,
            "status": "SOURCE_UNAVAILABLE",
            "message":
                "TruthLens could not access this source.",
            "source_accessible": False,
            "title": "",
            "text_preview": ""
        })

    # --------------------------------------------------
    # Unexpected error
    # --------------------------------------------------

    except Exception as error:

        print("Verification error:", error)

        return jsonify({
            "success": False,
            "status": "VERIFICATION_ERROR",
            "message":
                "An unexpected error occurred while checking the source.",
            "source_accessible": False,
            "title": "",
            "text_preview": ""
        })


# ==================================================
# VERIFICATION API
# ==================================================

@app.route("/verify", methods=["POST"])
def verify():
    return run_verification()


# This also supports the deployed frontend
@app.route("/api/verify", methods=["POST"])
def api_verify():
    return run_verification()


# ==================================================
# LOCAL SERVER
# ==================================================

if __name__ == "__main__":

    print("======================================")
    print("TruthLens is ready.")
    print("Open http://127.0.0.1:5000")
    print("======================================")

    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )
