from flask import Flask, request, jsonify
from pathlib import Path
import joblib

app = Flask(__name__)

# Project root = folder containing app.py, model files, etc.
ROOT = Path(__file__).resolve().parent.parent

MODEL_PATH = ROOT / "truthlens_model.pkl"
VECTORIZER_PATH = ROOT / "truthlens_vectorizer.pkl"


def load_model():
    model = joblib.load(MODEL_PATH)
    vectorizer = joblib.load(VECTORIZER_PATH)
    return model, vectorizer


@app.route("/api", methods=["GET"])
def health():
    return jsonify({
        "status": "online",
        "message": "TruthLens AI ML backend is running."
    })


@app.route("/api/predict", methods=["POST"])
def predict():

    data = request.get_json(silent=True)

    if not data:
        return jsonify({
            "error": "No data received."
        }), 400

    text = data.get("text", "").strip()
    url = data.get("url", "").strip()

    if not text:
        return jsonify({
            "error": "Please enter a news claim."
        }), 400

    try:
        model, vectorizer = load_model()

        text_vector = vectorizer.transform([text])

        prediction = model.predict(text_vector)[0]

        probabilities = model.predict_proba(text_vector)[0]

        fake_probability = float(probabilities[0])
        real_probability = float(probabilities[1])

        if prediction == 0:

            confidence = fake_probability

            if confidence >= 0.65:
                result = "FAKE"
            else:
                result = "UNCERTAIN"

        else:

            confidence = real_probability

            if confidence >= 0.65:
                result = "REAL"
            else:
                result = "UNCERTAIN"

        confidence_percentage = round(confidence * 100, 2)

        return jsonify({
            "result": result,
            "confidence": confidence_percentage,
            "fake_probability": round(fake_probability * 100, 2),
            "real_probability": round(real_probability * 100, 2),
            "article_url": url,
            "message": "Prediction generated by the TruthLens machine-learning model."
        })

    except Exception as e:

        return jsonify({
            "error": "The TruthLens ML model could not be loaded.",
            "details": str(e)
        }), 500


if __name__ == "__main__":
    app.run()
